Add MGRS Extension from code in stactools-package for sentinel2
stac-utils/pystac pull request #1088
Opened 2023-04-07 21:32 UTC by jsignell

**Related Issue(s):**

- #778

**Description:**

Code from: https://github.com/stactools-packages/sentinel2/blob/main/src/stactools/sentinel2/mgrs.py
Example from: https://github.com/stac-extensions/mgrs/blob/main/examples/item.json

Added pytest-style tests, docs

**PR Checklist:**

- [x] `pre-commit` hooks pass locally
- [x] Tests pass (run `scripts/test`)
- [x] Documentation has been updated to reflect changes, if applicable
- [x] This PR maintains or improves overall codebase code coverage.
- [ ] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac/blob/main/CHANGELOG.md). See [the docs](https://pystac.readthedocs.io/en/latest/contributing.html#changelog) for information about adding to the changelog.

2023-04-10 18:55 UTC, jsignell commented on pystac/extensions/mgrs.py
This is copied wholesale from stac-tools. I found a few minor issues in testing. I will call these out inline

2023-04-10 18:56 UTC, jsignell commented on pystac/extensions/mgrs.py
> +        self._set_property(UTM_ZONE_PROP, validated_utm_zone(v), pop_if_none=True)
This was `pop_if_none=False` in the original, but None is not allowed according to the spec.

2023-04-10 18:57 UTC, jsignell commented on pystac/extensions/mgrs.py
> +            return MgrsExtension(obj)
This has a `cast` around it in the original, but mypy didn't need it.

2023-04-11 11:32 UTC, gadomski requested changes

2023-04-11 11:32 UTC, gadomski commented on CHANGELOG.md
> +- MGRS Extension [#1088](https://github.com/stac-utils/pystac/pull/1088)
```suggestion
- MGRS Extension ([#1088](https://github.com/stac-utils/pystac/pull/1088))
```

2023-04-12 22:11 UTC, gadomski approved these changes

2023-04-12 22:22 UTC, merged

2023-06-07 15:36 UTC, philvarner commented
Thanks for doing this @jsignell