Make sure that get_items is backwards compatible
stac-utils/pystac pull request #1139
Opened 2023-06-01 14:59 UTC by jsignell

**Related Issue(s):**

- Closes #1138 

**Description:**

I didn't quite go so far as reverting, but I did make the change backwards compatible by not relying on the new kwarg internally. I ran the pystac-client tests locally and the one that was failing in https://github.com/stac-utils/pystac-client/issues/485 passes now.

Note: I didn't add tests.There should be only 2 lines that aren't tested (the ones in the TypeError blocks), so it seemed like more trouble than it was worth, but just let me know if you think they are necessary. 

**PR Checklist:**

- [x] `pre-commit` hooks pass locally
- [ ] Tests pass (run `scripts/test`)
- [ ] Documentation has been updated to reflect changes, if applicable
- [ ] This PR maintains or improves overall codebase code coverage.
- [ ] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac/blob/main/CHANGELOG.md). See [the docs](https://pystac.readthedocs.io/en/latest/contributing.html#changelog) for information about adding to the changelog.

2023-06-01 21:09 UTC, jsignell commented
I'm taking a look at the tests to get the coverage back up. I think I probably took a lot of `get_item` testing out in my original PR.

2023-06-01 21:54 UTC, jsignell commented
phew ok, hopefully that'll do it

2023-06-01 21:55 UTC, jsignell commented on pystac/catalog.py
> -                items = self.get_all_items()
I couldn't figure out how to hit this and it doesn't crop up in pystac-client tests, so maybe it was unreachable? It's hurting my brain to think about it.

2023-06-02 12:43 UTC, gadomski requested changes

2023-06-02 13:20 UTC, jsignell commented on pystac/collection.py
> +            return super().get_item(id, recursive=recursive)
I didn't really check for other ways - let me see.

2023-06-02 15:49 UTC, gadomski approved these changes

2023-06-02 19:27 UTC, merged