Return Link Object after adding a child or item #1159
stac-utils/pystac pull request #1160
Opened 2023-06-14 14:17 UTC by m-mohr

**Related Issue(s):**

- #1159

**Description:**

Catalog: `add_child` and `add_item` return a Link object instead of None [#1159](https://github.com/stac-utils/pystac/issues/1159)

**PR Checklist:**

- [x] `pre-commit` hooks pass locally
- [x] Tests pass (run `scripts/test`)
- [x] Documentation has been updated to reflect changes, if applicable
- [ ] This PR maintains or improves overall codebase code coverage.
- [x] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac/blob/main/CHANGELOG.md). See [the docs](https://pystac.readthedocs.io/en/latest/contributing.html#changelog) for information about adding to the changelog.

2023-06-14 15:27 UTC, gadomski requested changes
With this change, I think `Catalog.add_children()` should now return a list of created links as well.

2023-06-14 17:49 UTC, m-mohr commented on CHANGELOG.md
> +- `add_child` and `add_item` return a Link object instead of None [#1159](https://github.com/stac-utils/pystac/issues/1159)
Done

2023-06-14 17:58 UTC, m-mohr commented on tests/test_catalog.py
> +        assert isinstance(link, pystac.Link)
Done

2023-06-14 18:00 UTC, m-mohr commented
@gadomski Thanks for the review. I've applied the changes according to your suggestions and also implemented (and tested) that add_children and add_items return lists of links.

2023-06-15 14:12 UTC, gadomski approved these changes

2023-06-15 14:20 UTC, merged