Include some json schemas within pystac
stac-utils/pystac pull request #1165
Opened 2023-06-16 20:05 UTC by jsignell

**Related Issue(s):**

- closes #1007, related to #1162

**Description:**

I pulled a lot of @gadomski's work off the v2 branch, but left the existing validation mechanism in place, just calling out to the new stuff when the schema is local.

**PR Checklist:**

- [ ] `pre-commit` hooks pass locally
- [ ] Tests pass (run `scripts/test`)
- [ ] Documentation has been updated to reflect changes, if applicable
- [ ] This PR maintains or improves overall codebase code coverage.
- [ ] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac/blob/main/CHANGELOG.md). See [the docs](https://pystac.readthedocs.io/en/latest/contributing.html#changelog) for information about adding to the changelog.

2023-06-20 12:17 UTC, gadomski requested changes

2023-06-20 12:17 UTC, gadomski commented on pystac/validation/jsonschemas/extensions/eo/v1.1.0/schema.json
I'm less sure that we want to include extension schemas in this library. The extensions release more quickly and with less publicity, and so we get less of a win for more complexity. IMO if folks need performance gains while validating extensions, they should build and hold onto their `JsonSchemaSTACValidator` and its associated cache.

2023-06-20 13:38 UTC, gadomski commented on pystac/validation/local_validator.py
> +        return cast(Dict[str, Any], json.load(f))
Yeah, I don't understand all the intricacies, but I _think_ `importlib` tries to reserve the right to lay things out differently, e.g. I think this method support zipped dependencies. I wish I grokked it all better, though 😞.

2023-06-20 14:20 UTC, jsignell commented on pystac/validation/local_validator.py
> +        return cast(Dict[str, Any], json.load(f))
ooh zipping. Yeah that makes sense.

2023-06-21 15:55 UTC, gadomski approved these changes

2023-06-21 18:09 UTC, jsignell commented
Oh rats. merge queue is never going to work with that failing schema lookup

2023-06-21 20:41 UTC, merged