Fix item field ordering on `save_object`
stac-utils/pystac pull request #1423
Opened 2024-10-02 19:04 UTC by moradology

**Related Issue(s):**

- #587

**Description:**
This PR fixes item field ordering in accordance with the order defined [here](https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#item-fields). Additionally, I've fixed what appears to be a small configuration error in pre-commit.config.yaml such that ruff-format wasn't actually fixing ill-formatted files.

**PR Checklist:**

- [x] Pre-commit hooks and tests pass (run `scripts/test`)
- [x] Documentation has been updated to reflect changes, if applicable
- [x] This PR maintains or improves overall codebase code coverage.
- [ ] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac/blob/main/CHANGELOG.md). See [the docs](https://pystac.readthedocs.io/en/latest/contributing.html#changelog) for information about adding to the changelog.

2024-10-02 19:05 UTC, moradology commented
@jsignell I think this ought to be good to go

2024-10-03 11:30 UTC, gadomski requested changes

2024-10-03 11:30 UTC, gadomski commented on pystac/item.py
> +            "properties": self.properties,
Need to remove the (now redundant) conditional assignments below: https://github.com/stac-utils/pystac/pull/1423/files#diff-c235f14269d2641c490a6ec16abb7ab96c1f7d4e2ca4514b0ade666b2094469eR377-R381

2024-10-03 11:30 UTC, gadomski commented on tests/test_item.py
> +
We're only changing `to_dict`, so we could just serialize to a dict and check that? No need for a temp file.

2024-10-03 15:07 UTC, gadomski approved these changes

2024-10-03 15:13 UTC, merged