Create CODE_OF_CONDUCT.md
stac-utils/pystac pull request #399
Opened 2021-06-02 18:36 UTC by BobinMathew

**Related Issue(s):** #
Issue #385

**Description:**
Created a CODE_OF_CONDUCT.md that points to  Code of Conduct in the STAC spec repo. This makes the code of conduct consistent with the STAC repo's code of conduct

**PR Checklist:**

- [ ] Code is formatted (run `scripts/format`)
- [ ] Tests pass (run `scripts/test`)
- [ ] This PR maintains or improves overall codebase code coverage.
- [ ] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac/blob/develop/CHANGELOG.md). See [the docs](https://pystac.readthedocs.io/en/latest/contributing.html#changelog) for information about adding to the changelog.

2021-06-02 19:51 UTC, gadomski commented on CODE_OF_CONDUCT.md
> +Stac-Utils follows the [STAC spec Code of Conduct](https://github.com/radiantearth/stac-spec/blob/master/CODE_OF_CONDUCT.md).
```suggestion
# pystac Community Code of Conduct

pystac follows the [STAC spec Code of Conduct](https://github.com/radiantearth/stac-spec/blob/master/CODE_OF_CONDUCT.md).
```

2021-06-03 14:54 UTC, duckontheweb reviewed
Thanks for contributing this @BobinMathew, and for recognizing the gap.

I think it might be good to at least include the [Our Pledge](https://github.com/radiantearth/stac-spec/blob/master/CODE_OF_CONDUCT.md#our-pledge) portion of the Code of Conduct in full in this document and then reference the STAC Code of Conduct for details on the specific standards. It seems important to make a clear statement in this repo about the kind of environment that are hoping to foster so that newcomers know it's something that's important within the community.

Also, the STAC spec Code of Conduct lists stac-spec-admins@googlegroups.com as the contact to report abuses and unacceptable behavior. Do we need a different email, or can we use that one here (@cholmes)?

2021-06-04 13:56 UTC, BobinMathew commented
- [X] Included Pledge
- [ ] contact details pending...

2021-06-04 18:08 UTC, duckontheweb commented
@BobinMathew We are going to use the STAC Project Steering Committee email (stac-psc@radiant.earth) as our point of contact. It sounds like the `stac-spec` repo may also update their Code of Conduct to use this email at some point. 

I think it would be good to include that information in this repo as well to make it as easy as possible for someone to report a violation or other problem.

2021-06-05 13:41 UTC, BobinMathew commented
* [x]  Included Pledge
* [x]  contact details added

2021-06-07 13:19 UTC, duckontheweb approved these changes
This looks good to me, thanks for contributing this @BobinMathew!

I'd like to get approval from at least @cholmes and @lossyrob as well and give other folks a chance to comment if they'd like.

2021-06-07 13:58 UTC, lossyrob requested changes
Made some suggestions for small changes

2021-06-07 13:58 UTC, lossyrob commented on CODE_OF_CONDUCT.md
> +# pystac Community Code of Conduct
Spelling elsewhere is PySTAC when used in this sort of context

```suggestion
# PySTAC Community Code of Conduct
```

2021-06-07 13:58 UTC, lossyrob commented on CODE_OF_CONDUCT.md
> +reported by contacting the project team at [stac-psc-admins](mailto:stac-psc@radiant.earth). All
```suggestion
reported by contacting the [STAC Project Steering Committee](mailto:stac-psc@radiant.earth). All
```

2021-06-07 13:58 UTC, lossyrob commented on CODE_OF_CONDUCT.md
> +pystac follows the [STAC spec Code of Conduct](https://github.com/radiantearth/stac-spec/blob/master/CODE_OF_CONDUCT.md).
```suggestion
PySTAC follows the [STAC spec Code of Conduct](https://github.com/radiantearth/stac-spec/blob/master/CODE_OF_CONDUCT.md).
```

2021-06-07 14:28 UTC, lossyrob approved these changes

2021-06-07 16:00 UTC, BobinMathew commented
Thanks everyone 😀

2021-06-10 15:50 UTC, cholmes approved these changes

2021-06-10 16:43 UTC, merged

2021-06-10 16:43 UTC, duckontheweb commented
Thanks again for the contribution @BobinMathew!