Bump jsonschema minimum version to avoid RefResolutionError
stac-utils/pystac pull request #857
Opened 2022-07-26 13:16 UTC by duckontheweb

**Related Issue(s):**

- Closes #845

**Description:**

Validating Collections with the Processing Extension led to a RefResolutionError when using `jsonschema` < 4.0. Since 4.0.1 was yanked from PyPi, we now pin to `jsonschema>=4.0.1`.

**PR Checklist:**

- [x] Code is formatted (run `pre-commit run --all-files`)
- [x] Tests pass (run `scripts/test`)
- [ ] Documentation has been updated to reflect changes, if applicable
- [x] This PR maintains or improves overall codebase code coverage.
- [ ] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac/blob/main/CHANGELOG.md). See [the docs](https://pystac.readthedocs.io/en/latest/contributing.html#changelog) for information about adding to the changelog.

2022-07-26 13:27 UTC, m-mohr approved these changes
Tested with 4.0.1 and the reported error doesn't occur anymore.

2022-07-27 14:18 UTC, gadomski requested changes
There's a `test-validation-error.json` file at the top level of the repository -- is that intentional? IMO that file should be in `tests/data-files` and should be checked w/ a regression test.

2022-07-27 14:22 UTC, duckontheweb commented
> There's a `test-validation-error.json` file at the top level of the repository -- is that intentional? IMO that file should be in `tests/data-files` and should be checked w/ a regression test.

Oops, sorry. I was using that to reproduce the original error. I reverted the commit that added this.

2022-07-27 14:24 UTC, gadomski approved these changes

2022-07-27 14:30 UTC, merged