Add timespec to datetime_to_str util function.
stac-utils/pystac pull request #929
Opened 2022-12-29 18:05 UTC by imanshafiei540

**Related Issue(s):** #

- Helps fix https://github.com/stac-utils/pystac/issues/927

**Description:**
Currently `datetime_to_str` function in `utils` truncates all microseconds if the microsecond in `datetime` object is equal to zero.
I've added an optional input (`timespec`) to control this ability. The default behavior is like before, but If users want to retrieve the result with `microseconds`, they can pass `timespec = "microseconds"` to the `datetime_to_str` function, and the result with microseconds will return.

**PR Checklist:**

- [ ] Code is formatted (run `pre-commit run --all-files`)
- [ ] Tests pass (run `scripts/test`)
- [ ] Documentation has been updated to reflect changes, if applicable
- [ ] This PR maintains or improves overall codebase code coverage.
- [ ] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac/blob/main/CHANGELOG.md). See [the docs](https://pystac.readthedocs.io/en/latest/contributing.html#changelog) for information about adding to the changelog.

2022-12-29 18:09 UTC, gadomski requested changes
Can you add a unit test demonstrating the expected behavior? Thanks!

2022-12-29 18:26 UTC, imanshafiei540 commented
I've added a new unit test. Thank you so much for reviewing.

2022-12-30 12:13 UTC, gadomski requested changes
So sorry, I should have caught this on first review ... can you also add a description of the `timespec` argument to the `datetime_to_str` docstring, e.g. at https://github.com/stac-utils/pystac/pull/929/files#diff-98860a0104c5b45415729e4d1252380cfcc767add4a1a88561d80d5cdee4828cR309. Thanks.

2022-12-30 17:34 UTC, imanshafiei540 commented
No worries at all. It was my mistake. Also, add my changes in the changelog. Thanks.

2022-12-30 17:38 UTC, gadomski approved these changes

2022-12-30 17:42 UTC, merged